# Site settings
title: Kaffee Kantate
author: Kay
description: Life in Vancouver, Tech, Coffee, etc
paginate: 7
baseurl: ""#http://blog.kaffeekantate.xyz
#url: http://blog.kaffeekantate.xyz

permalink: /:title/
tag_permalink_style: pretty
exclude: [Gemfile, Gemfile.lock, README.md, Rakefile]
sass:
  sass_dir: _sass
  style: :compressed

#gems:
  #- jekyll-sitemap

# Build settings
markdown: kramdown

# tagging
tag_page_layout: tag_page
tag_page_dir: tag
#tag_feed_layout: tag_feed
#tag_feed_dir: tag

#info
email: kay.yamagishi.work@gmail.com
github_username: kay-
personal_info: About 4 years at System integrator in Tokyo and now studying at BCIT, Vancouver

